apiVersion: batch/v1
kind: Job

metadata:
  name: pwt-eu-smoke-job

spec:
  template:
    spec:
      restartPolicy: Never

      containers:
        - name: pwt-eu-smoke
          image: localhost:5000/pwt-eu:latest
          imagePullPolicy: IfNotPresent

          env:
            - name: ENV
              value: "__ENV__"

            - name: OLLAMA_URL
              value: "http://host.docker.internal:11434"

            - name: OLLAMA_MODEL
              value: "llama3.2:3b"

            - name: AGENT_MAX_STEPS
              value: "3"

            - name: AI_FAILURE_TIMEOUT_MS
              value: "180000"

          command:
            - /bin/bash
            - -c
            - |
              npx playwright test \
                --project=__BROWSER__ \
                --grep "@smoke" \
                --workers=__WORKERS__ \
                --reporter=blob

              TEST_EXIT=$?

              echo "Smoke execution completed."
              echo "Keeping Pod alive for artifact collection..."

              sleep 25

              exit $TEST_EXIT

  backoffLimit: 0

---

apiVersion: batch/v1
kind: Job

metadata:
  name: pwt-eu-regression-job

spec:
  template:
    spec:
      restartPolicy: Never

      containers:
        - name: pwt-eu-regression
          image: localhost:5000/pwt-eu:latest
          imagePullPolicy: IfNotPresent

          env:
            - name: ENV
              value: "__ENV__"

            - name: OLLAMA_URL
              value: "http://host.docker.internal:11434"

            - name: OLLAMA_MODEL
              value: "llama3.2:3b"

            - name: AGENT_MAX_STEPS
              value: "3"

            - name: AI_FAILURE_TIMEOUT_MS
              value: "180000"

          command:
            - /bin/bash
            - -c
            - |
              npx playwright test \
                --project=__BROWSER__ \
                --grep "@regression" \
                --workers=__WORKERS__ \
                --reporter=blob

              TEST_EXIT=$?

              echo "Regression execution completed."
              echo "Keeping Pod alive for artifact collection..."

              sleep 25

              exit $TEST_EXIT

  backoffLimit: 0